"""Global review policy. Scores are evidence grades, not calibrated probabilities."""
PRICE_CHANGE_REVIEW_THRESHOLD = 0.20
REVIEW_TARGET_STORES = 3
REVIEW_MATCHES_PER_STORE = 3
REVIEW_WEIGHTS = {"stores": 20, "matches": 20, "query": 20, "current": 25, "spread": 15}
REVIEW_QUERY_CREDIT = {"HIGH": 1.0, "MEDIUM": 0.65, "LOW": 0.25}
REVIEW_MISSING_CURRENT_CREDIT = 0.25
REVIEW_SCORE_BOUNDARIES = (25, 45, 65, 85)
REVIEW_FLAG_PENALTIES = {
    "VERY HIGH RISK": 25, "HIGH RISK": 15, "LOW SEARCH CONFIDENCE": 5,
    "ONE STORE ONLY": 5, "TARGET SIZE WARNING": 20, "REQUEST ERROR": 10,
}
REVIEW_FLAG_CAPS = {"NO MATCHES": 1, "VERY HIGH RISK": 2, "HIGH RISK": 3,
                    "TARGET SIZE WARNING": 2, "REQUEST ERROR": 3}
REVIEW_UNKNOWN_FLAG_PENALTY = 10
REVIEW_LARGE_CHANGE_CAP = 3
REVIEW_PRICE_DECIMALS = 2
REVIEW_POLICY_VERSION = 1
